### ISSUE TITLE
Mistakes in French text

### ISSUE THREAD

**Issue by veler** [veler/clipboardzanager#32]
A user found some grammar issues in the French version of the app.

![capture2](https://user-images.githubusercontent.com/3747805/30170153-2c5b4090-93a3-11e7-8de3-c8669ec4de40.jpg)
![capture1](https://user-images.githubusercontent.com/3747805/30170162-3465906a-93a3-11e7-965c-72b8687a4840.jpg)
![21371244_1298740836903605_2006502063549807919_n](https://user-images.githubusercontent.com/3747805/30242505-712df154-954c-11e7-88bc-68787f882d7d.jpg)

**Comment by vmichalak** [comment]
I don't know if it's really a bug ... 😆

**Comment by veler** [comment]
It's not but it must be fix and I put it here so I don't forget xD
