### ISSUE TITLE
The app crash after copying a large text

### ISSUE THREAD

**Issue by veler** [veler/clipboardzanager#5]
On Android, when we copy a (too?) large text from an app, ClipboardZanager intercept the data but crash.

**Environment :** 
Android 7.0

**Steps to reproduce :** 
* Open ``Chrome on Android``.
* Navigate to [https://en.m.wikipedia.org/wiki/%22Hello,_World!%22_program](https://en.m.wikipedia.org/wiki/%22Hello,_World!%22_program)
* Be sure to extend the sections ``Purpose``, ``History``, ``Variations``, ``See also``, ``References``, ``External links``.
* Do a ``Select All`` on the content.
* ``Copy``.

![screenshot_20170830-140905](https://user-images.githubusercontent.com/3747805/29895108-bf4da0c2-8d8c-11e7-8903-9e185130a641.png)

**Comment by vmichalak** [comment]
Problem solved on my version, i doing some tests and push it after ;)
