### ISSUE TITLE
Bug avec plusieurs écrans

### ISSUE THREAD

**Issue by LotuxPunk** [veler/clipboardzanager#58]
Hey !
Comme beaucoup, j'ai découvert ce projet grâce à GuillaumeSlash, déjà beau boulot !
Par contre, petit bug avec les utilisateurs qui ont pleins d'écrans comme moi. Sur l'écran principale, aucun soucis, par contres les auxiliaires ça bug un peu, voir les screenshots :
![2017-12-14 1](https://user-images.githubusercontent.com/16562647/34004544-77ec453e-e0f8-11e7-82a1-085f3d7dd533.png)
![2017-12-14](https://user-images.githubusercontent.com/16562647/34004545-7807bbde-e0f8-11e7-8394-423a025861a0.png)

J'ai pas encore le niveau en C# pour proposer un fix, mais je pense que la solution se situe dans le fait que mes écrans sont de tailles différentes et que pour le coup ils sont configuré à des hauteurs différentes.

Merci d'avance et à bientôt !

Clément V.

**Comment by veler** [comment]
Hello,

Merci du partage. C'est un bug connu. :)
La récupération de la véritable résolution d'écran en considérant le HDPI n'était pas facile. J'avais écrit un article à ce sujet : http://blog.velersoftware.com/2016/10/recuperer-vraie-resolution-decran-c-windows-ecarte-lanus/

J'ai constaté ce bug chez certains utilisateurs, et plus récemment sur ma machine personnelle (je pouvais ENFIN reproduire le problème !). Depuis que j'avais upgradé de W10 Creator Update à Fall Creator Update, j'avais ce soucis. Je n'ai pas trouvé de résultat très logique lorsque j'ai débogué ça. Et puis finalement en faisant une clean installation de Windows, le soucis a disparu. Ca me fait donc penser à un soucis lié à une migration, une mise à jour ou un driver. Mais j'aimerais bien étudier ça de nouveau.

Petites questions : 
- Est-ce que la barre s'affiche correctement sur le premier écran?
- Si vous paramétrez l'app pour que la barre s'affiche en bas de l'écran, apparait-elle correctement sur tous les écrans?
- Quelle est la résolution d'écran et le pourcentage d'agrandissement de l'interface de chaque écran, et quel est l'écran primaire?

Merci :)

**Comment by LotuxPunk** [comment]
Hey !
Merci de cette célérité !
Article hyper intéressant ! Merci du partage ! (J'ai rencontré un problème avec une bête UWP Webview, et ça pourrait être ma solution, donc je suis aux anges 👼 )
Je vous laisse juge du résultat, mais il y a bien un souci vers le bas aussi : 
![2017-12-14 4](https://user-images.githubusercontent.com/16562647/34016873-c8b2d3c2-e123-11e7-89de-ef1e7b9b81e3.png)
![2017-12-14 3](https://user-images.githubusercontent.com/16562647/34016874-c8cec56e-e123-11e7-93bd-d2b42b0b7706.png)
![2017-12-14 5](https://user-images.githubusercontent.com/16562647/34016875-c8e874f0-e123-11e7-8720-c4b5177b6a88.png)

Donc : 
- Aucun souci sur l'écran "principale" qui est le "2" sur l'image ci-dessous.
-Par contre depuis le haut ou le bas le 1 et le 3 présentent des problèmes. Depuis le haut, le 1 ne s'affiche même pas, le 3 à 1/2. Depuis le bas, ça apparait mais de façon un peu aléatoire sur le 1 et le 3.

Alors, respectivement : 

1. 1366 * 768 - 100%
2. 1920 * 1200 - 100%
3. 1280 * 1024 - 100%

Les 3 compères sont branchés à la même GPU (1070, même si je ne pense pas que ce soir nécessaire à l'équation.)

Je pense avoir été complet, je reste disponible !
Bonne soirée !

Clément V.

**Comment by LotuxPunk** [comment]
![image](https://user-images.githubusercontent.com/16562647/34017137-bd420aac-e124-11e7-8cf1-334a07f07447.png)

**Comment by veler** [comment]
Hello,

OKKKK ! Je viens de saisir le problème et je viens de comprendre comment le reproduire (il était temps...).

En fait, dans tes paramètres d'affichages, les écrans 1 et 3 sont en dessous de 2. Tu peux avec la souris cliquer sur le rectangle "1" et le glisser en haut, au même niveau que le "2". Redémarre CZ, et là ça devrait fonctionner sur cet écran.

Je comprends le soucis et n'avais jamais fait attention à ça => l'API ne tient pas compte de la marge en haut tout simplement. Je vais étudier comment améliorer ça.

Honnêtement je n'aurais pas vraiment beaucoup de temps, je pars en vacances dans 2 jours pendant 4 mois avec un simple sac à dos et une tablette, donc je serais assez limité et je n'aurais pas de double écran pour reproduire le problème haha.

Si je n'ai pas push de fix d'ici Dimanche, si vous lisez ce message, voici la méthode qui contient le bug : https://github.com/veler/clipboardzanager/blob/80b090a5f8ae0dc9dc6abe7b9a1511b9f6ed3bf2/ClipboardZanager/Sources/ClipboardZanager.Core.Desktop/ComponentModel/SystemInfoHelper.cs#L147

Merci ! :)

**Comment by LotuxPunk** [comment]
Hey ! Pas de souci !
Au pire, sur l'écran principale y a pas de problème donc ça va. :)
Je vais attendre un patch bien calmement, et peut-être regarderais-je le code si j'ai la foi et la capacité ! 👨‍💻 
Bonne journée & bonne vacances !

**Comment by veler** [comment]
Bug fixé : https://github.com/veler/clipboardzanager/commit/1b89f8f5f5cf99d7f9a133bd5f976b1fb27a132c
