### ISSUE TITLE
Suggestion to Detect password

### ISSUE THREAD

**Issue by arond1** [veler/clipboardzanager#59]
Hi, I heard about you have some problems to detect password.
So the suggestion :
Before deleting the password check if it contain at least one uppercase, one downcase, and one number whitout any space (because a huge part of internet website and other give this method to build a password). Sorry if you have already found and thank you for your huge work.

A random French

**Comment by veler** [comment]
Hi,
Thank you for sharing this idea. It's almost how it works actually : 

https://github.com/veler/clipboardzanager/blob/4e4071688ff6b1d1ab193d81e629e189c888046f/ClipboardZanager/Sources/ClipboardZanager.Core.Desktop/Services/DataService.cs#L166

Right now, it considers that a data is a password if : 
- The data comes from a web browser only.
- Has at least one uppercase.
- Has number.
- Has special characters.
- And is between 8 and 32 characters.

But if I copy a partial URL from YouTube, for example, "?v=Fx7cejcoq4U&t=0s", it matches those conditions. Imagine that the user copy a short code from StackOverflow, the same thing can happen.

We could think "let's keep only what comes from a password box", but it's very hard to implement and I don't think it's always possible to copy a data from a password box. Also a password is not necessarily wrote in a password box. So I'm not sure it worth it to take this direction.

I though to this problem several times, and I start to believe this feature was not a good idea. Detecting a credit card number is very easy. Detecting a password has too many scenarios where we could think the data is a password where it's not.
Except in a password generator on internet, where does a user would want to copy a password? In a password manager like Dashlane or PasswordZanager maybe. But there is already a feature designed to avoid keeping any data from those apps...

So, right now, except if someone has a cool implementation idea, I'm thinking about removing this specific feature. What do you guys think about? I don't see a proper solution to be sure it's a password, we can only suppose it.

**Comment by arond1** [comment]
You are right, i don't think about this cases. maybe just put a a text box/notification to prevent user they should have a password in there clipboard and allow them to remove it by clicking a buton in the notification ?
-----------
One other parameter is that : paqqword are not with other text (i don't see any case where you copy multiple password or password with some text at the same time)
Sorry for my english level i'm french :)

**Comment by veler** [comment]
Yes, exactly :) That's why it's hard.

No worries for your English ;)
